---
# https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
- block:
  - name: MongoDB | Import public GPG Key
    apt_key:
        keyserver: keyserver.ubuntu.com
        id: 0C49F3730359A14518585931BC711F9BA15703C6
    tags: mongodb

  - name: MongoDB | Add repository into sources list
    apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu {{ sys_release }}/mongodb-org/3.4 multiverse
        state: present
    tags: mongodb

  - name: MongoDB | Install package
    apt:
        name: mongodb-org
        update_cache: yes
    tags: mongodb

  - name: MongoDB | Create dbpath directory
    file:
      path: "/data/db"
      state: directory
    
  - name: MongoDB | Enable service at boot time
    systemd:
      name: mongod
      state: restarted
      enabled: yes
    tags: mongodb

  become: yes
