---

- name: Nginx | Install nginx
  apt: pkg=nginx
  become: yes
  tags: nginx

- name: Nginx | Setup reverse proxy
  become: yes
  template: src=nginx_site_config.j2 dest=/etc/nginx/sites-available/default
  tags: nginx

- name: Nginx | Start nginx
  service: name=nginx state=restarted
  become: yes
  tags: nginx
