---

- block:

  - name: Nginx | Install service
    apt: pkg=nginx

  - name: Nginx | Setup reverse proxy
    template: src=nginx_site_config.j2
              dest=/etc/nginx/sites-available/default
              owner={{ nodeapp_user }}
              group={{ nodeapp_group }}

  - name: Nginx | Start service
    service: name=nginx state=restarted

  become: yes
