---

- name: Ensure that the application file permissions are set properly
  file: path={{ env_path }}
        recurse=yes
        owner={{ nodeapp_user }}
        group={{ nodeapp_group }}
        state=directory

- name: Create a symlink for legacy node issue
  file: src=/usr/bin/nodejs
        dest=/usr/bin/node
        state=link

- name: Create log directory
  file: path={{ application_log_dir }}
        owner={{ nodeapp_user }}
        group={{ nodeapp_group }}
        state=directory
