---

- name: Git | Setup the repo
  git: repo={{ git_repo }} dest={{ app_path }} accept_hostkey=yes
  when: setup_git_repo
  register: git_cloned

- name: Git | Build the server
  npm: path={{ app_path }}
  when: git_cloned.changed
